# Generated by Django 5.1.2 on 2024-12-08 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nike1', '0003_product1'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('img', models.ImageField(upload_to='nikeimg')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cat', models.CharField(max_length=100)),
            ],
        ),
    ]
